
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXJkQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM0MjE4MDcwLCJleHAiOjE3MzQyNTQwNzB9.3tSa7_pd129WR-8FOEV_zh2Zlq6XZNGgjCkPwr3TJ0w


###

# curl -X PUT http://localhost:8080/api/users/me
#-H "Content-Type: application/json"
#-H "Authorization: Bearer <"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcm9maWxlMDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzQyMTcwMjQsImV4cCI6MTczNDI1MzAyNH0.37MH0SweLU_J-XVF_tU3hiBg5OIjTQiXDENk1DLrQwE">"
#-d '{"name": "Batati", "phone": "+123456789"}'
PUT http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXJkQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM0MjE4MDcwLCJleHAiOjE3MzQyNTQwNzB9.3tSa7_pd129WR-8FOEV_zh2Zlq6XZNGgjCkPwr3TJ0w
Content-Type: application/json

{
  "name": "saleh",
  "phone": "+123456789"
}

###

