name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: Lint Frontend Code
        run: |
          npm install
          npm run lint

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: lint-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm test
  ui-ux-tests:
    name: UI/UX Tests
    runs-on: ubuntu-latest
    needs: [test-frontend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install Dependencies
        run: |
          npm install
      - name: Start Frontend Server
        run: |
          npm run dev &
        env:
          PORT: 3000

      - name: Wait for Frontend Server
        run: |
          npx wait-on http://localhost:3000
      - name: Run Cypress Tests
        run: |
          npx cypress run
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [ui-ux-tests]
    if: success()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging Server
        run: |
          echo "Deploying to Staging Environment..."
          # Add deployment commands here
